repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/isort
    rev: b2d5c47
    hooks:
    -   id: isort
        args: ["--profile", "black", "-l", "120"]
-   repo: https://github.com/psf/black
    rev: aa31a11
    hooks:
    -   id: black
        args: ["-l", "120"]
